sudo: false
language: node_js
node_js:
  - "6.2"
  - "5"
  - "5.1"
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm run test
- npm run integrate
after_success:
- git config --global user.email "robot@health-samurai.io"
- git config --global user.name "Travis CI Deployer"
- if [ -n "$TRAVIS_TAG" ]; then ./script/bower-release.sh; fi
- if [ -n "$TRAVIS_TAG" ]; then sed -i "s/0.0.0/$TRAVIS_TAG/g" package.json; fi
deploy:
  provider: npm
  email: niquola@gmail.com
  api_key:
    secure: XOnOloUekdn7IFgHUzaRx+XxjCVSjWBsAOpsp468omWBn88ifiUY++jt2VplXICcbceFx9EpLb7IHxl2fl0sTwJo0lwwPZDaH+QV2GuP4ue2jh3DeNNSdnOVWYDf4r1drtF7i6+jJN4Ns9jhl+/tjCJmDmNdh6azP6HaTBf2TUI=
  on:
    tags: true
    repo: FHIR/fhir.js
